export const SUBMIT = 'SUBMIT';
export const UPDATE_CARDNUMBER ='UPDATE_CARDNUMBER';
export const UPDATE_HOLDERNAME ='UPDATE_HOLDERNAME';
export const UPDATE_CARDCVV ='UPDATE_CARDCVV';
export const UPDATE_EXPIREMONTH ='UPDATE_EXPIREMONTH';
export const UPDATE_EXPIREYEAR ='UPDATE_EXPIREYEAR';
export const UPDATE_NUMBER ='UPDATE_NUMBER';
export const RESET = 'RESET';
